In [3]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image
import requests  # 외부에 있는 이미지를 가져올 때 사용
from io import BytesIO

url = 'https://cdn.pixabay.com/photo/2018/10/01/09/21/pets-3715733_960_720.jpg'

response = requests.get(url)
pic = Image.open(BytesIO(response.content))

pic_arr = np.asarray(pic)

In [4]:
pic_arr

array([[[215, 124, 141],
        [215, 124, 141],
        [215, 124, 141],
        ...,
        [233, 145, 169],
        [233, 145, 169],
        [233, 145, 169]],

       [[215, 124, 141],
        [215, 124, 141],
        [215, 124, 141],
        ...,
        [233, 145, 169],
        [233, 145, 169],
        [233, 145, 169]],

       [[215, 124, 141],
        [215, 124, 141],
        [215, 124, 141],
        ...,
        [233, 145, 169],
        [233, 145, 169],
        [233, 145, 169]],

       ...,

       [[210, 132, 145],
        [211, 133, 146],
        [211, 133, 146],
        ...,
        [231, 153, 179],
        [230, 152, 178],
        [229, 151, 177]],

       [[210, 132, 145],
        [211, 133, 146],
        [211, 133, 146],
        ...,
        [229, 151, 177],
        [229, 151, 177],
        [229, 151, 177]],

       [[210, 132, 145],
        [211, 133, 146],
        [211, 133, 146],
        ...,
        [228, 150, 176],
        [230, 152, 178],
        [231, 153, 179]]

이미지 출력(OpenCV)
 - from google.colab.patches import cv2_imshow (Colab에서 cv2를 불러올 때)
   - 원래는 cv2.imshow

In [5]:
cv2.imshow('DOG', pic_arr)
cv2.waitKey(0)             # 이미지가 응답없음이 뜰 때
cv2.destroyAllWindows() 

OpenCV의 채널 순서
   - openCV를 통해 영상(이미지)을 다룰 때의 채널 순서는 B G R
   - matplotlib은 R G B 순서


cv2.cvtColor() : convert to color
   - image array, 변경할 색공간을 인자로 넣어줌
   - 변경할 색공간은 여러가지가 있다
      - cv2.COLOR_BGR2RGB
      - cv2.COLOR_RGB2GRAY
      - cv2.COLOR_GRAY2RGB
      - ...

In [6]:
image = cv2.cvtColor(pic_arr, cv2.COLOR_RGB2BGR)
cv2.imshow('dog', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
print(image[0][0])

[215 124 141]


   - image, pic_arr 비교
      - 0 1 2 인덱스 중 0, 2가 바뀐 것을 알 수 있음

In [17]:
print(image[0][0])
print(pic_arr[0][0])

[215 124 141]
[141 124 215]


   - (참고) array[:, :, ::-1]을 통해서도 인덱스 순서를 바꿀 수 있음


In [20]:
temp_arr = pic_arr[:, :, ::-1]

In [23]:
print(pic_arr[0][0])
print(temp_arr[0][0])

[141 124 215]
[215 124 141]
