torch <-> numpy
   - Torch Tensor(텐서)를 Numpy array(배열)로 변환 가능
      - numpy()
      - from_numpy()
   - (참고)
      - Tensor가 CPU상에 있다면 Numpy 배열은 메모리 공간을 공유하므로 하나가 변하면, 다른 하나도 변함

In [2]:
import torch
import numpy as np

In [3]:
a = torch.ones(7)

print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [4]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [5]:
a.add_(1)
print(a, b)

tensor([2., 2., 2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2. 2. 2.]


In [7]:
a = np.ones(7)
b = torch.from_numpy(a)      # 넘파이에서 텐서로 변환
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)
