파이토치(PyTorch)의 구성요소
  1. torch : 텐서를 생성하는 라이브러리

  2. torch.autograd : 자동미분 기능을 제공하는 라이브러리

  3. torch.nn : 신경망을 생성하는 라이브러리

  4. torch.multiprocessing : 병렬처리 기능을 제공하는 라이브러리

  5. torch.utils : 데이터 조작 등 유틸리티 기능 제공

  6. torch.legacy(/nn/.optim): Torch로부터 포팅해온 코드

  7. torch.onnx : ONNX(Open Neural Network Exchange) - 서로 다른 프레임워크 간의 모델을 공유할 때 사용

텐서(Tensors)
   넘파이(Numpy)의 ndarray와 유사
   GPU를 사용한 연산 가속도 가능

In [2]:
import torch
torch.__version__

'1.10.1'

초기화 되지 않는 텐서

In [3]:
x = torch.empty(4, 2)

x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

무작위로 초기화된 텐서

In [4]:
x = torch.rand(4, 2)

x

tensor([[0.4605, 0.6293],
        [0.1538, 0.2972],
        [0.3046, 0.2243],
        [0.7511, 0.9577]])

dtype이 long, 0으로 채워진 텐서

In [5]:
x = torch.zeros(4, 2, dtype=torch.long)

x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [6]:
x = torch.tensor([3, 2.3])  # 값을 직접 지정

x

tensor([3.0000, 2.3000])

In [7]:
x = x.new_ones(2, 4, dtype=torch.double)  # 지정된 변수안에서 또 다른 텐서를 생성

x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [21]:
x = torch.randn_like(x, dtype=torch.float)   # x라는 변수의 텐서프레임은 그대로 가져오되, 값들은 랜덤으로 채움

x

tensor([[ 2.6771,  0.1677,  0.4953, -1.5056],
        [ 0.5565, -1.2561, -0.5362,  0.8778]])

텐서의 크기

In [22]:
x.size()

torch.Size([2, 4])

In [91]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(y)

print(x.grad)

tensor([-522119.4375,  224820.3125, 1439204.8750])
