텐서의 연산(operations)

In [1]:
import torch

덧셈 1

In [3]:
x = torch.rand(2, 4)
x

tensor([[0.4816, 0.5257, 0.3127, 0.9978],
        [0.3257, 0.2900, 0.7194, 0.4564]])

In [4]:
y = torch.rand(2, 4)
print(y)
x + y

tensor([[0.0259, 0.8675, 0.4614, 0.5405],
        [0.8741, 0.0263, 0.0051, 0.0169]])


tensor([[0.5076, 1.3933, 0.7741, 1.5383],
        [1.1999, 0.3163, 0.7245, 0.4733]])

덧셈 2

In [5]:
torch.add(x, y) # add라는 함수를 이용하여 덧셈을 해준다

tensor([[0.5076, 1.3933, 0.7741, 1.5383],
        [1.1999, 0.3163, 0.7245, 0.4733]])

덧셈 3 ( 결과텐서를 인자로 제공)

In [6]:
result = torch.empty(2, 4)  # result라는 빈 공간을 만든다
torch.add(x, y, out=result)  # x,y 를 더한 값을 result에 넣는다

result       # result만 출력해도 x,y가 더한 값을 출력할 수 있다.

tensor([[0.5076, 1.3933, 0.7741, 1.5383],
        [1.1999, 0.3163, 0.7245, 0.4733]])

덧샘 4 (in-place방식)

In [7]:
print(x, y)

y.add_(x)   # y += x 와 같다. 즉 y에 x를 더한 후 그 값을 다시 y에 저장한다는 뜻
y

tensor([[0.4816, 0.5257, 0.3127, 0.9978],
        [0.3257, 0.2900, 0.7194, 0.4564]]) tensor([[0.0259, 0.8675, 0.4614, 0.5405],
        [0.8741, 0.0263, 0.0051, 0.0169]])


tensor([[0.5076, 1.3933, 0.7741, 1.5383],
        [1.1999, 0.3163, 0.7245, 0.4733]])