view
  - 텐서의 크기(size)나 모양(shape)을 변경

In [2]:
import torch

In [3]:
x = torch.randn(4, 5)
y = x.view(20)           # 2차원의 텐서를 쭉 나열된 형태로 출력, 즉 1차원 텐서로 바뀜
z = x.view(5, -1)        # x의 텐서의 shape을 변경

print(x)
print(y)
print(z)

tensor([[-0.6984, -0.5993, -1.1867, -0.0773,  0.2250],
        [-0.5453,  1.2168,  0.4741, -0.9119,  1.3085],
        [-0.4203,  0.2201,  1.8024,  0.2192,  0.7347],
        [ 1.4662, -0.1076,  1.0363,  0.0125,  1.6532]])
tensor([-0.6984, -0.5993, -1.1867, -0.0773,  0.2250, -0.5453,  1.2168,  0.4741,
        -0.9119,  1.3085, -0.4203,  0.2201,  1.8024,  0.2192,  0.7347,  1.4662,
        -0.1076,  1.0363,  0.0125,  1.6532])
tensor([[-0.6984, -0.5993, -1.1867, -0.0773],
        [ 0.2250, -0.5453,  1.2168,  0.4741],
        [-0.9119,  1.3085, -0.4203,  0.2201],
        [ 1.8024,  0.2192,  0.7347,  1.4662],
        [-0.1076,  1.0363,  0.0125,  1.6532]])
