기울기(Gradient)
   - 역전파 : .backward()를 통해 역전파 계산 가능


In [11]:
import torch

In [12]:
x = torch.ones(3, 3, requires_grad=True)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [13]:
y = x + 5  # 
y

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)

In [17]:
print(y.grad_fn)

z = y * y * 2
out = z.mean()

print(z, out)  # grad_fn에 연산 정보가 저장?


tensor([[72., 72., 72.],
        [72., 72., 72.],
        [72., 72., 72.]], grad_fn=<MulBackward0>) tensor(72., grad_fn=<MeanBackward0>)


In [18]:
a = torch.randn(3, 3)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True


In [19]:
out.backward()

In [20]:
print(x.grad)

tensor([[5.3333, 5.3333, 5.3333],
        [5.3333, 5.3333, 5.3333],
        [5.3333, 5.3333, 5.3333]])


In [27]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([-1664.3563,    63.1403,   211.6636], grad_fn=<MulBackward0>)


In [28]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(y)

print(x.grad)

tensor([-3408601.7500,   129311.4297,   433487.1250])


   - with torch.no_grad()를 허용하여 gradient의 업데이트를 하지 않음

In [29]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
   print((x ** 2).requires_grad) 

True
True
False


   - detach(): 내용물(content)은 같지만 requires_grad가 다른 새로운 Tensor를 가져올 때

In [30]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
