자동 미분 흐름 다시보기(1)
   - 계산 흐름
   a -> b -> c -> out

   - backward()를 통해
   a <- b <- c<- out을 계산하면 미분값이 a.grad에 채워짐

In [1]:
import torch

In [2]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [3]:
a = torch.ones(2, 2, requires_grad=True)
print(a)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [14]:
print("a.data: ", a.data)
print("a.grad : ", a.grad)         # 계산이 이뤄져야 결과치가 반환됨
print("a.grad_fn : ", a.grad_fn)   # 계산이 이뤄져야 결과치가 반환됨

a.data:  tensor([[1., 1.],
        [1., 1.]])
a.grad :  tensor([[6., 6.],
        [6., 6.]])
a.grad_fn :  None


   - b = a + 2

In [6]:
b = a + 2
print(b)        # add로 연산 grad_fn=<AddBackward0>

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


   - c = b ** 2

In [9]:
c = b ** 2
print(c)   # 제곱 연산 grad_fn=<PowBackward0>

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [10]:
out = c.sum()
print(out)   # grad_fn=<SumBackward0>

tensor(36., grad_fn=<SumBackward0>)


In [11]:
print(out)
out.backward()

tensor(36., grad_fn=<SumBackward0>)


   a, b, c의 data, grad, grad_fn, out 비교

In [13]:
print("a.data: ", a.data)
print("a.grad : ", a.grad)
print("a.grad_fn : ", a.grad_fn)

a.data:  tensor([[1., 1.],
        [1., 1.]])
a.grad :  tensor([[6., 6.],
        [6., 6.]])
a.grad_fn :  None


In [15]:
print("b.data: ", b.data)
print("b.grad : ", b.grad)
print("b.grad_fn : ", b.grad_fn)

b.data:  tensor([[3., 3.],
        [3., 3.]])
b.grad :  None
b.grad_fn :  <AddBackward0 object at 0x00000153D47202B0>


C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten\src\ATen/core/TensorBody.h:417.)
  return self._grad


In [16]:
print("c.data: ", c.data)
print("c.grad : ", c.grad)
print("c.grad_fn : ", c.grad_fn)

c.data:  tensor([[9., 9.],
        [9., 9.]])
c.grad :  None
c.grad_fn :  <PowBackward0 object at 0x00000153D47206A0>


C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten\src\ATen/core/TensorBody.h:417.)
  return self._grad


자동 미분 흐름 다시보기(2)
   - grad값을 넣어서 backward
   - 아래의 코드에서 .grad값이 None은 gradient값이 필요하지 않기 때문

In [17]:
x = torch.ones(3, requires_grad=True)
y = (x ** 2)
z = y ** 2 + x
out = z.sum()

print(out)

tensor(6., grad_fn=<SumBackward0>)


In [18]:
grad = torch.Tensor([0.1, 1, 100])
z.backward(grad)

In [19]:
print("x.data: ", x.data)
print("x.grad : ", x.grad)
print("x.grad_fn : ", x.grad_fn)

x.data:  tensor([1., 1., 1.])
x.grad :  tensor([  0.5000,   5.0000, 500.0000])
x.grad_fn :  None


In [20]:
print("y.data: ", y.data)
print("y.grad : ", y.grad)
print("y.grad_fn : ", y.grad_fn)

y.data:  tensor([1., 1., 1.])
y.grad :  None
y.grad_fn :  <PowBackward0 object at 0x00000153E985FF40>


C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten\src\ATen/core/TensorBody.h:417.)
  return self._grad


In [21]:
print("z.data: ", x.data)
print("z.grad : ", x.grad)
print("z.grad_fn : ", x.grad_fn)

z.data:  tensor([1., 1., 1.])
z.grad :  tensor([  0.5000,   5.0000, 500.0000])
z.grad_fn :  None
