In [3]:
import numpy as np

In [4]:
x = np.array(range(1, 31))
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [5]:
x = x.reshape(6, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
# split 함수 정의
def split_xy(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column-1
        
        if y_end_number > len(dataset):
            break
        tmp_x = dataset[i:x_end_number, :-1]
        tmp_y = dataset[x_end_number-1:y_end_number, -1]
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)

x_sp, y_sp = split_xy(x, 2, 3)

x_sp.shape, y_sp.shape

((3, 2, 4), (3, 3))

In [11]:
x_sp, y_sp

(array([[[ 1,  2,  3,  4],
         [ 6,  7,  8,  9]],
 
        [[ 6,  7,  8,  9],
         [11, 12, 13, 14]],
 
        [[11, 12, 13, 14],
         [16, 17, 18, 19]]]),
 array([[10, 15, 20],
        [15, 20, 25],
        [20, 25, 30]]))

In [81]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(10, input_shape=(2, 4)))
model.add(Dense(64, activation='relu'))
model.add(Dense(3))

model.compile(loss='mse', optimizer='adam')
model.fit(x_sp, y_sp, epochs=1000, batch_size=1)

Epoch 1/1000
3/3 [==============================] - 1s 1ms/step - loss: 428.1372
Epoch 2/1000
3/3 [==============================] - 0s 1ms/step - loss: 426.2792
Epoch 3/1000
3/3 [==============================] - 0s 997us/step - loss: 424.1239
Epoch 4/1000
3/3 [==============================] - 0s 998us/step - loss: 422.3695
Epoch 5/1000
3/3 [==============================] - 0s 998us/step - loss: 420.4577
Epoch 6/1000
3/3 [==============================] - 0s 998us/step - loss: 418.5201
Epoch 7/1000
3/3 [==============================] - 0s 998us/step - loss: 416.7617
Epoch 8/1000
3/3 [==============================] - 0s 1ms/step - loss: 414.8584
Epoch 9/1000
3/3 [==============================] - 0s 997us/step - loss: 412.9399
Epoch 10/1000
3/3 [==============================] - 0s 1ms/step - loss: 410.9914
Epoch 11/1000
3/3 [==============================] - 0s 997us/step - loss: 408.7462
Epoch 12/1000
3/3 [==============================] - 0s 1ms/step - loss: 406.8233
Epoch 13/10

In [83]:
loss = model.evaluate(x_sp, y_sp)
print("loss : ", loss)

1/1 [==============================] - 0s 11ms/step - loss: 0.0023
loss :  0.0023073724005371332


In [84]:
pred_y = x[4:6, :4]
pred_y = pred_y.reshape(1, 2, 4)
pred = model.predict(pred_y)
print(pred)

# results = model.predict(x_sp)
# print(results)

[[21.366589 26.715734 32.04598 ]]
